import connectDB from "@/lib/mongodb";
import { ImageConfiguration, ImageConfigSchema } from "@/models/ImageConfig";
import sharp from "sharp";
import { createUploadthing, type FileRouter } from "uploadthing/next";
import { z } from "zod";

const f = createUploadthing();

// this will run once image is uploaded from user\
// all of this happens on server and passes configId variable to the client
export const ourFileRouter = {
  imageUploader: f({
    image: {
      maxFileSize: "4MB",
      maxFileCount: 1,
    },
  })
    //? client passes to server configId using startUpload(acceptedFile,{configId:undefined "in step1"})
    //?.onUploadComplete function runs on server and sends back the configId to client so it can redirect to the next step
    //? with searchParam (id), whether its new id which means added new imageItem in database
    //? or just the old id which means i updated an exsiting imageItem
    //? to the server here, and server validates type to be string
    .input(
      z.object({
        configId: z.string().optional(),
        options: ImageConfigSchema.shape.options.optional(),
      }),
    )
    .middleware(async ({ input }) => {
      return { input }; //means {input : input} == {input : {configId:"1234"} }
      //key here is named input not the actual input object it doesnt make any sense
    })
    .onUploadComplete(async ({ metadata, file }) => {
      const { configId, options } = metadata.input;
      // when upload is complete, the file.ufsUrl is the link of the image.
      // u can search the link on google it wil work because uploadthing hosts the image online
      // and the link is given to u {file.ufsUrl}
      const response = await fetch(file.ufsUrl);
      const buffer = await response.arrayBuffer();
      const imageMetaData = await sharp(buffer).metadata();
      const { width, height } = imageMetaData;
      await connectDB();
      if (!configId) {
        //in step 1 the configId is undefined which means i want to add the image properties to the database
        const imageDetails = await ImageConfigurationcreate({
          width: width || 500,
          height: height || 500,
          imageUrl: file.ufsUrl,
        });
        // _id is generated by mongoDb, but its and object field so to use it as string u can say .toString() or use .id give by monogoDb as string
        return { configId: imageDetails.id };
      } else {
        //there is configId, so the items exists in database, so i want to update the value of element of that id
        await ImageConfigurationupdateOne(
          { _id: configId }, // filter
          {
            // WITH $set - only updates specified fields
            $set: {
              // in step 2 we will upload the cropped image using startUpload() from uploadthing,
              // it will pass through this function again onUploadComplete() as the file.ufsUrl
              // so now i put it in the database as the croppedImageUrl
              croppedImageUrl: file.ufsUrl,
              options,
            },
          },
        );
      }
      return { configId };
    }),
} satisfies FileRouter;

export type OurFileRouter = typeof ourFileRouter;
