import type { Metadata } from "next";
import { Geist, Geist_Mono, Recursive } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/nav-bar";
import { Separator } from "@/components/ui/separator";
import WindowDimensions from "@/components/breakpoint";

const recursice = Recursive({
  subsets: ["latin"],
  variable: "--font-recursive",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${recursice.variable} font-recursive overflow-x-hidden bg-slate-50 antialiased`}
      >
        <Navbar />
        {/* <WindowDimensions /> */}
        {children}
      </body>
    </html>
  );
}
