import type { Metadata } from "next";
import {  Recursive } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/nav-bar";
import WindowDimensions from "@/components/breakpoint";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";

const recursice = Recursive({
  subsets: ["latin"],
  variable: "--font-recursive",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${recursice.variable} font-recursive overflow-x-hidden bg-slate-50 antialiased`}
      >
        <Navbar />
        <WindowDimensions />
        <main className="flex min-h-[calc(100dvh-4rem)] flex-col">
          <div className="flex-1">{children}</div>
          <Footer />
        </main>
        <Toaster />
      </body>
    </html>
  );
}
